# Generated by Django 5.2 on 2026-05-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('stage_of_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('examination_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='dissertation.clinicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RetinalScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('grade', models.IntegerField(blank=True, choices=[(0, 'No DR'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Proliferative DR')], null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('image_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='dissertation.patient')),
            ],
        ),
    ]
